development:
  clients:
    default:
      database: rails_test_development
      hosts:
        - localhost:27017
      options:
        connect: :direct
        server_selection_timeout: 1

test:
  clients:
    default:
      database: rails_test_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
